// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWp1Gj2djQzkxlI8LWnOzKhw9_sO-s0k',
    appId: '1:987157819436:web:f660366f1bb06628496189',
    messagingSenderId: '987157819436',
    projectId: 'cwt-ecom-admin-panel',
    authDomain: 'cwt-ecom-admin-panel.firebaseapp.com',
    storageBucket: 'cwt-ecom-admin-panel.firebasestorage.app',
    measurementId: 'G-E2V7VBSBFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpAr70JzmmqKlIdo6GniLNktclIF3tJRM',
    appId: '1:987157819436:android:3ab3fd3f6ef3f744496189',
    messagingSenderId: '987157819436',
    projectId: 'cwt-ecom-admin-panel',
    storageBucket: 'cwt-ecom-admin-panel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJufa7YiyECcEK-hPgd70QBrHI9N3_x80',
    appId: '1:987157819436:ios:6a0a8885a0f90c12496189',
    messagingSenderId: '987157819436',
    projectId: 'cwt-ecom-admin-panel',
    storageBucket: 'cwt-ecom-admin-panel.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJufa7YiyECcEK-hPgd70QBrHI9N3_x80',
    appId: '1:987157819436:ios:6a0a8885a0f90c12496189',
    messagingSenderId: '987157819436',
    projectId: 'cwt-ecom-admin-panel',
    storageBucket: 'cwt-ecom-admin-panel.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPWp1Gj2djQzkxlI8LWnOzKhw9_sO-s0k',
    appId: '1:987157819436:web:31a0431a2b798fd7496189',
    messagingSenderId: '987157819436',
    projectId: 'cwt-ecom-admin-panel',
    authDomain: 'cwt-ecom-admin-panel.firebaseapp.com',
    storageBucket: 'cwt-ecom-admin-panel.firebasestorage.app',
    measurementId: 'G-803LBC3X16',
  );

}